version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - abhijeetnarvekar
  - package-ecosystem: "nuget"
    directory: "/Acrolinx.Adapter.Demo.Sidebar.Cpp/"
    schedule:
      interval: "daily"
    reviewers:
      - abhijeetnarvekar
  - package-ecosystem: "nuget"
    directory: "/Acrolinx.Demo.Sidebar.Cpp/"
    schedule:
      interval: "daily"
    reviewers:
      - abhijeetnarvekar
