// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "acrolinxsidebar1.h"

/////////////////////////////////////////////////////////////////////////////
// CAcrolinxsidebar1

IMPLEMENT_DYNCREATE(CAcrolinxsidebar1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CAcrolinxsidebar1 properties

/////////////////////////////////////////////////////////////////////////////
// CAcrolinxsidebar1 operations
